# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- ado-pipelines

pool:
  vmImage: windows-latest

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(7d20f677-bdb3-46c2-bac3-25a8fe5890a0)'
    appType: 'webApp'
    appName: 'angular-adder'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod --build-optimizer
  displayName: 'npm install and build'
  

